ecommerce:
  property: Ecommerce Profile Prod
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_hexagonal
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-circular-references: true
server:
  port: 8081
jwt:
  secret_key: 7A24432646294A404E635266556A586E3272357538782F4125442A472D4B6150
  expiration_time: 86400000A
